openai_api_key = "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"
anthropic_api_key = "k-ant-api03-wHzDBdqHqNqBLb3MOxUorlK7iKq72o8s1W0S5O9xuBkShnZvN3etFkr49RZTF515Kw7ofpTdX4Xj2G-oKT6GWQ-Gp6OhQAA"
cohere_api_key = "0OJ7PC4fm97P18FFdOlQ3FFq6ou5Jfcu9j37ThlU"
gemini_api_key = "AIzaSyAP1PoLJVlk_l-xCQhjQ62nYBmNy_9_Ey0"
